<a href="https://colab.research.google.com/github/quickgrid/CodeLab/blob/master/tensorflow/TF_Keras_ResNet101_Filter_Shape_Weights_and_MaxPooling_Strided_Convolution_on_Odd_Input.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
!wget "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/African_Bush_Elephant.jpg/1200px-African_Bush_Elephant.jpg" -O "elephant.jpg"

--2021-04-24 15:14:14--  https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/African_Bush_Elephant.jpg/1200px-African_Bush_Elephant.jpg
Resolving upload.wikimedia.org (upload.wikimedia.org)... 103.102.166.240, 2001:df2:e500:ed1a::2:b
Connecting to upload.wikimedia.org (upload.wikimedia.org)|103.102.166.240|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 407327 (398K) [image/jpeg]
Saving to: ‘elephant.jpg’

elephant.jpg        100%[===================>] 397.78K  1.79MB/s    in 0.2s    

2021-04-24 15:14:14 (1.79 MB/s) - ‘elephant.jpg’ saved [407327/407327]



In [34]:
from tensorflow.keras.applications import ResNet101
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.resnet import preprocess_input, decode_predictions
import numpy as np

model = ResNet101(weights='imagenet')

img_path = 'elephant.jpg'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

preds = model.predict(x)
# decode the results into a list of tuples (class, description, probability)
# (one such list for each sample in the batch)
print('Predicted:', decode_predictions(preds, top=3)[0])

Predicted: [('n02504458', 'African_elephant', 0.89527893), ('n01871265', 'tusker', 0.10053827), ('n02504013', 'Indian_elephant', 0.003901293)]


In [35]:
model.summary()

Model: "resnet101"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_3 (InputLayer)            [(None, 224, 224, 3) 0                                            
__________________________________________________________________________________________________
conv1_pad (ZeroPadding2D)       (None, 230, 230, 3)  0           input_3[0][0]                    
__________________________________________________________________________________________________
conv1_conv (Conv2D)             (None, 112, 112, 64) 9472        conv1_pad[0][0]                  
__________________________________________________________________________________________________
conv1_bn (BatchNormalization)   (None, 112, 112, 64) 256         conv1_conv[0][0]                 
__________________________________________________________________________________________

In [43]:
print(len(model.layers[2].weights))

2


In [40]:
print(model.layers[2].name)
print(model.layers[2].weights[0].shape)
print(model.layers[2].weights[1].shape)

conv1_conv
(7, 7, 3, 64)
(64,)


In [37]:
print(model.layers[2].name)
print(model.layers[2].weights)

conv1_conv
[<tf.Variable 'conv1_conv/kernel:0' shape=(7, 7, 3, 64) dtype=float32, numpy=
array([[[[ 2.04881709e-02,  1.74432080e-02, -1.19661177e-02, ...,
           1.61669459e-02, -1.07464865e-01, -2.39391886e-02],
         [ 4.93109189e-02,  3.46018225e-02, -4.73766541e-03, ...,
           1.22750150e-02,  1.21253334e-01, -1.56366359e-02],
         [ 1.42431771e-02,  7.63520133e-03, -1.78580452e-03, ...,
           3.06030363e-02, -1.64227169e-02, -2.00326163e-02]],

        [[ 3.33432555e-02, -5.44109615e-03, -8.14679638e-03, ...,
          -1.14415102e-02, -3.28667350e-02, -2.75743101e-02],
         [ 2.80981157e-02, -1.19839655e-03, -7.15339277e-03, ...,
          -1.88215412e-02,  6.10436872e-02, -2.52630003e-02],
         [ 3.01602427e-02, -1.44053092e-02, -6.37047086e-03, ...,
          -2.03179941e-02, -5.22239357e-02, -9.02882218e-03]],

        [[ 1.43847391e-02, -1.01541206e-02,  1.65149686e-04, ...,
          -1.43255284e-02, -4.83350866e-02, -3.36065330e-02],
         [ 

In [38]:
print(model.layers[7].name)
print(model.layers[7].weights)

conv2_block1_1_conv
[<tf.Variable 'conv2_block1_1_conv/kernel:0' shape=(1, 1, 64, 64) dtype=float32, numpy=
array([[[[ 0.00160399, -0.00254265, -0.01731922, ..., -0.01651942,
           0.01513864, -0.0354646 ],
         [ 0.01515921, -0.00627845,  0.00166968, ...,  0.01461547,
           0.03117803,  0.11374122],
         [ 0.00282309,  0.00229593,  0.03237155, ...,  0.0035359 ,
          -0.03562421, -0.00834576],
         ...,
         [-0.02377483, -0.0010978 , -0.02749332, ..., -0.08129182,
          -0.00911469, -0.04912051],
         [ 0.02666844,  0.00969497,  0.07066278, ..., -0.02592005,
          -0.01759226, -0.02110136],
         [-0.0223264 ,  0.00080224, -0.08305199, ...,  0.006657  ,
           0.0217971 , -0.03367427]]]], dtype=float32)>, <tf.Variable 'conv2_block1_1_conv/bias:0' shape=(64,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0

## Enumerrate layers, get filter shape and counts

In [39]:
for i, layer in enumerate(model.layers):
  print(layer.name)
  if layer.weights:
    print(layer.weights[0].shape)
    print(layer.weights[1].shape)
  print('-' * 30)

input_3
------------------------------
conv1_pad
------------------------------
conv1_conv
(7, 7, 3, 64)
(64,)
------------------------------
conv1_bn
(64,)
(64,)
------------------------------
conv1_relu
------------------------------
pool1_pad
------------------------------
pool1_pool
------------------------------
conv2_block1_1_conv
(1, 1, 64, 64)
(64,)
------------------------------
conv2_block1_1_bn
(64,)
(64,)
------------------------------
conv2_block1_1_relu
------------------------------
conv2_block1_2_conv
(3, 3, 64, 64)
(64,)
------------------------------
conv2_block1_2_bn
(64,)
(64,)
------------------------------
conv2_block1_2_relu
------------------------------
conv2_block1_0_conv
(1, 1, 64, 256)
(256,)
------------------------------
conv2_block1_3_conv
(1, 1, 64, 256)
(256,)
------------------------------
conv2_block1_0_bn
(256,)
(256,)
------------------------------
conv2_block1_3_bn
(256,)
(256,)
------------------------------
conv2_block1_add
----------------------

## Tensorflow odd size max pooling

In [63]:
import tensorflow as tf
x = tf.constant(123, shape=(255, 255, 64))
x = tf.reshape(x, [1, 255, 255, 64])
max_pool_2d = tf.keras.layers.MaxPooling2D(pool_size=(2, 2),
   strides=(2, 2), padding='valid')
max_pool_2d(x)

<tf.Tensor: shape=(1, 127, 127, 64), dtype=int32, numpy=
array([[[[123, 123, 123, ..., 123, 123, 123],
         [123, 123, 123, ..., 123, 123, 123],
         [123, 123, 123, ..., 123, 123, 123],
         ...,
         [123, 123, 123, ..., 123, 123, 123],
         [123, 123, 123, ..., 123, 123, 123],
         [123, 123, 123, ..., 123, 123, 123]],

        [[123, 123, 123, ..., 123, 123, 123],
         [123, 123, 123, ..., 123, 123, 123],
         [123, 123, 123, ..., 123, 123, 123],
         ...,
         [123, 123, 123, ..., 123, 123, 123],
         [123, 123, 123, ..., 123, 123, 123],
         [123, 123, 123, ..., 123, 123, 123]],

        [[123, 123, 123, ..., 123, 123, 123],
         [123, 123, 123, ..., 123, 123, 123],
         [123, 123, 123, ..., 123, 123, 123],
         ...,
         [123, 123, 123, ..., 123, 123, 123],
         [123, 123, 123, ..., 123, 123, 123],
         [123, 123, 123, ..., 123, 123, 123]],

        ...,

        [[123, 123, 123, ..., 123, 123, 123],
       

In [61]:
import tensorflow as tf

x = tf.constant(1.2, shape=(255, 255, 3))
x = tf.reshape(x, [1, 255, 255, 3])

filters = tf.constant(1, shape=(7, 7, 3, 64))
print(filters.shape)

c_2d = tf.keras.layers.Conv2D(64, (7, 7), strides=(2, 2), padding='same')
c_2d(x)

(7, 7, 3, 64)


<tf.Tensor: shape=(1, 128, 128, 64), dtype=float32, numpy=
array([[[[ 0.3616757 ,  0.31876758,  0.05620833, ..., -0.29590946,
          -0.0124218 , -0.04166604],
         [ 0.39273798,  0.15709518,  0.178353  , ..., -0.29409108,
          -0.15928258,  0.07180213],
         [ 0.3212573 ,  0.11182682,  0.21234743, ..., -0.3306471 ,
          -0.22350407,  0.03042488],
         ...,
         [ 0.3212573 ,  0.11182682,  0.21234743, ..., -0.3306471 ,
          -0.22350407,  0.03042488],
         [ 0.13556142,  0.03989841,  0.30985907, ..., -0.21200046,
          -0.11733862,  0.00426467],
         [ 0.14898741, -0.11460671,  0.13324943, ..., -0.01762782,
          -0.04263708,  0.1736779 ]],

        [[ 0.43350613,  0.47604042,  0.24361578, ..., -0.22147384,
           0.19290674, -0.12387875],
         [ 0.4850395 ,  0.28295964,  0.48855528, ..., -0.24008101,
          -0.04890559,  0.04525775],
         [ 0.418552  ,  0.21771789,  0.6166462 , ..., -0.2634935 ,
          -0.10577077,  0.